import Link from "next/link";
export default function ApplyHelp() {
  return <div className="content apply-help"><div className="eyebrow">Tailor → approve → apply → report</div><h1 className="page-title">Your application workflow</h1><p>Approve the exact tailored resume once. The local browser worker fills the application, verifies the attachment and submits, then reports the result.</p>
    <section className="panel"><h2>Automatic applications after your approval</h2><ol><li>Tailor the job and review the resulting resume.</li><li>In the Apply tab, select <strong>Approve resume &amp; apply</strong>. That authorizes submission to this job with this exact version.</li><li>The local worker opens a dedicated Chrome window, uses your saved answers and approved resume, and checks the attached PDF before submitting.</li><li>Read the application report for the employer confirmation, resume version, answers entered and any unresolved questions.</li></ol><p>The browser worker starts with the local app. It uses your existing Codex account and free local Playwright; there is no paid API fallback. Your Codex usage limits still apply.</p><p>This application browser has its own saved Chrome profile, separate from your everyday tabs. If login is needed, the attempt pauses and leaves its browser window available for you to sign in. Then approve another attempt. Add missing factual answers in Application profile &amp; reusable answers. CAPTCHAs, assessments and unsupported form controls can also require your attention.</p><p>A confirmed employer receipt marks Applied. An uncertain submission is never automatically retried: check the employer site first to avoid duplicates. A new resume or application link requires approval again.</p></section>
    <section className="panel"><h2>Optional manual workflow with free Simplify</h2><ol><li>Open an application in AiadApply and review its resume changes.</li><li>In its <strong>Apply</strong> tab, download the PDF, confirm review and choose <strong>Use this reviewed resume</strong>. Then open the employer application.</li><li>Run Simplify Copilot. Then replace its default resume attachment with this job’s PDF. Verify the filename before submitting.</li><li>Review all answers and submit on the employer website.</li><li>Return to AiadApply and record the confirmation. A follow-up is scheduled automatically.</li></ol><p>Uploaded resume switching can depend on your Simplify plan. Manually replacing the employer’s attachment works without buying Simplify+.</p><a href="https://help.simplify.jobs/help/articles/2415391-using-copilot-to-autofill-applications" target="_blank" rel="noreferrer">Simplify’s autofill guide ↗</a></section>
    <section className="panel"><h2>AiadApply Assistant for Chrome</h2><p>A local helper for contact fields and your reviewed PDF. It previews recognized fields, keeps existing answers, and attaches a resume only when it finds an unambiguous resume upload. It never submits.</p><ol><li>Open <code>chrome://extensions</code> in Chrome and turn on Developer mode.</li><li>Choose <strong>Load unpacked</strong> and select <code>aiadapplyV2/extensions/application-assistant</code> in your Desktop project.</li><li>Save your contact details in AiadApply’s Answer kit. In the job’s Apply tab, confirm review and choose <strong>Download for AiadApply Assistant (optional)</strong>.</li><li>On the employer’s application, open AiadApply Assistant from Chrome’s toolbar and import that packet.</li><li>Confirm the job, preview the fields, then fill. Check the form and attachment before you submit.</li></ol><p>No account connection or paid API is needed. Packets contain personal information; keep them private. The helper only runs on the page you choose. Custom dropdowns, login screens, CAPTCHAs, work history, eligibility and demographic questions remain for you or Simplify.</p><p>If a portal changes its address after login, or embeds the form on another domain, use Simplify and upload the PDF manually. The helper stops when it cannot identify the intended job.</p></section>
    <section className="panel"><h2>Keep the right resume</h2><p>A packet contains one reviewed, validated PDF and its version. It does not follow later edits to a DOCX or a newly generated resume. Prepare a new packet for a new version; upload your edited document yourself if you revise it after download.</p><p>Opening a link, filling a form or generating a file never marks a job Applied. The confirmation you record is your submission record.</p></section>
    <Link href="/applications">Back to applications →</Link>
  </div>;
}
